name: inspection_app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # state management
  freezed_annotation: ^2.4.1
  flutter_hooks: ^0.20.1
  hooks_riverpod: ^2.1.1

  # util
  collection: ^1.17.2

  # ui
  cupertino_icons: ^1.0.2
  google_fonts: ^6.0.0
  dropdown_button2: ^2.3.9
  flutter_datetime_picker_plus: ^2.1.0
  image_picker: ^1.0.4
  cached_network_image: ^3.3.0
  animated_menu: ^1.0.2
  custom_pop_up_menu: ^1.2.4

  # firebase
  firebase_core: ^2.24.0
  cloud_firestore: ^4.13.3
  firebase_storage: ^11.5.3
  firebase_auth: ^4.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  freezed: ^2.4.2
  json_serializable: ^6.7.1
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
